# KVM/Libvirt and GNOME Boxes user VM images - NoCOW for BTRFS
d %h/.local/share/libvirt/images 0755 - - -
h %h/.local/share/libvirt/images - - - - +C
d %h/.local/share/gnome-boxes/images 0755 - - -
h %h/.local/share/gnome-boxes/images - - - - +C

# User container storage (Podman/Distrobox) - NoCOW for BTRFS
d %h/.local/share/containers/storage 0700 - - -
h %h/.local/share/containers/storage - - - - +C
d %h/.local/share/containers/storage/volumes 0700 - - -
h %h/.local/share/containers/storage/volumes - - - - +C

# Distrobox user storage
d %h/.local/share/distrobox 0700 - - -
h %h/.local/share/distrobox - - - - +C

# Rclone VFS cache - NoCOW for BTRFS
d %h/.cache/rclone 0755 - - -
h %h/.cache/rclone - - - - +C

# Podman volumes
d %h/.local/share/containers/storage/vfs 0700 - - -
h %h/.local/share/containers/storage/vfs - - - - +C
