# Ensure destination directories exist before copying configuration files
d %h/.var/app/com.brave.Browser/config 0755 - - -
d %h/.var/app/com.google.Chrome/config 0755 - - -
d %h/.config 0755 - - -

# Flatpak browsers
C %h/.var/app/com.brave.Browser/config/brave-flags.conf - - - - /usr/share/browser-configs/chromium-flags.conf
C %h/.var/app/com.google.Chrome/config/chrome-flags.conf - - - - /usr/share/browser-configs/chromium-flags.conf

# Native and Distrobox browsers
C %h/.config/chromium-flags.conf - - - - /usr/share/browser-configs/chromium-flags.conf
C %h/.config/brave-flags.conf - - - - /usr/share/browser-configs/chromium-flags.conf
C %h/.config/chrome-flags.conf - - - - /usr/share/browser-configs/chromium-flags.conf
