---
# yaml-language-server: $schema=https://schema.blue-build.org/module-list-v1.json

modules:
  - type: files
    files:
      - source: system
        destination: /

  - from-file: debloat.yml

  - from-file: repos.yml
  - from-file: fonts.yml

  - from-file: drivers.yml
  - from-file: packages.yml

  - from-file: tools.yml

  - from-file: kvm.yml

  - from-file: kargs.yml

  - from-file: systemd.yml

  # - from-file: flatpaks.yml
