[bluebuild]
image=ghcr.io/blue-build/cli:latest-distrobox
exported_bins=/usr/bin/bluebuild
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/podman
pull=true
replace=true
start_now=true
# Prevent GLX/Wayland driver mixing; use explicitly defined CDI for CUDA
nvidia=false
additional_flags="--device nvidia.com/gpu=all"
