# --- Wayland & Display Integration ---
--ozone-platform-hint=wayland

# --- GPU Acceleration & Video Decoding (AMD RX 6600 XT) ---
--ignore-gpu-blocklist
--enable-gpu-rasterization
# --enable-zero-copy # frequentemente causa corrupção de tiles/artefatos visuais no ecossistema Wayland com GPUs AMD (RX 6000 series) em versões recentes do Mesa.
--enable-features=WaylandWindowDecorations,VaapiVideoDecoder,VaapiIgnoreDriverChecks

# --- Privacy & Telemetry ---
--disable-breakpad
--no-pings
--disable-domain-reliability
