"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
command_timeout = 1000
palette = "kinoite"

format = """
$os$username$hostname$container$directory$git_branch$git_status$fill$cmd_duration
$character
"""

[palettes.kinoite]
fg = "#d9e0ee"
blue = "#7aa2f7"
green = "#9ece6a"
yellow = "#e0af68"
red = "#f7768e"
gray = "#6c7086"
cyan = "#7dcfff"
magenta = "#bb9af7"

[os]
disabled = false
style = "bold blue"
format = "[$symbol]($style)"

[os.symbols]
Fedora = " "
Ubuntu = " "
Arch = "󰣇 "
Debian = " "
Alpine = " "

[username]
show_always = false
style_user = "bold green"
style_root = "bold red"
format = "[$user ]($style)"

[hostname]
ssh_only = true
style = "bold yellow"
format = "[@$hostname ]($style)"

[container]
format = '[$symbol$name ](bold cyan)'
symbol = "󰏖 "

[directory]
style = "bold fg"
truncation_length = 4
truncate_to_repo = false
read_only = " 󰌾"
read_only_style = "bold red"
home_symbol = " ~"
truncation_symbol = "…/"
format = "[$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = " "
style = "bold blue"
format = "[$symbol$branch ]($style)"

[git_status]
style = "bold yellow"
format = "([$all_status$ahead_behind]($style) )"
conflicted = "󰞇 "
ahead = "⇡${count} "
behind = "⇣${count} "
diverged = "⇕⇡${ahead_count}⇣${behind_count} "
untracked = "󰋖 "
stashed = "📦 "
modified = "󰝌 "
staged = "󰐗 "
renamed = "󰑕 "
deleted = "󰮈 "

[fill]
symbol = " "

[cmd_duration]
min_time = 800
style = "gray"
format = "[󰔛 ${duration}]($style)"

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"
vimcmd_symbol = "[❮](bold blue)"
