monitor.alsa.rules = [
  {
    matches = [
      {
        "device.name" = "alsa_card.usb-C-Media_Electronics_Inc_MCHOSE_X9_0123456789AB-01"
      }
    ]
    actions = {
      update-props = {
        "api.alsa.soft-mixer" = false,
        "api.alsa.ignore-dB" = true
      }
    }
  }
]


