monitor.bluez.rules = [
  {
    matches = [
      {
        "device.name" = "bluez_card.79_06_BF_5C_9F_CE"
      }
    ]
    actions = {
      update-props = {
        "bluez5.enable-hw-volume" = false
      }
    }
  }
]
