name: build-amd
on:
  workflow_dispatch:

concurrency:
  group: build-pipeline-amd-${{ github.ref_name || github.run_id }}
  cancel-in-progress: true

jobs:
  build-amd:
    name: Build Custom AMD Image
    # O job de build agora é o primeiro a rodar
    runs-on: ubuntu-latest
    timeout-minutes: 45
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Build Custom AMD Image
        uses: blue-build/github-action@main
        with:
          recipe: recipe-amd.yml
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          retry_push_count: 3
          verify_install: true
          use_unstable_cli: false
          skip_checkout: true
          max_layers: 512
          chunkah: true
          maximize_build_space: true

  security-scan:
    name: Security scan (AMD)
    needs: build-amd # Garante que o build finalize antes do scan
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
      security-events: write
    steps:
      # O Trivy não precisa fazer checkout do código, ele vai puxar a imagem diretamente do registro do GitHub (ghcr.io)
      - name: Run Trivy scan (Image)
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25
        with:
          # Alterado de 'fs' para 'image'
          scan-type: image
          # O Trivy vai puxar a imagem recém-construída do seu repositório.
          # Lembre-se de verificar se o nome bate com o configurado no seu recipe.yml
          image-ref: ghcr.io/${{ github.repository_owner }}/kinoite-amd:latest
          format: sarif
          output: trivy-results.sarif
          severity: CRITICAL,HIGH
          ignore-unfixed: true

      - name: Upload SARIF report
        if: always()
        uses: github/codeql-action/upload-sarif@cdf488f595d80d6e07e03d4674febd5ab45fa938
        with:
          sarif_file: trivy-results.sarif
