name: build-amd-iso

on:
  schedule:
    - cron: "0 3 * * *" # Executa automaticamente todos os dias às 03:00 UTC (Madrugada)
  workflow_dispatch: # Permite a execução manual caso você precise gerar uma ISO pontual

concurrency:
  group: build-iso-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  security-scan:
    name: Security scan (nightly ISO)
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Run Trivy scan (filesystem)
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: fs
          scan-ref: .
          format: sarif
          output: trivy-results.sarif
          severity: CRITICAL,HIGH
          ignore-unfixed: true

      - name: Upload SARIF report
        if: always()
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: trivy-results.sarif

  generate-nightly-iso:
    name: Generate nightly ISO
    needs: security-scan
    runs-on: ubuntu-latest
    timeout-minutes: 90
    permissions:
      contents: write
      packages: write
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Detect Image Version
        id: detect
        run: |
          VERSION=$(skopeo inspect docker://ghcr.io/${{ github.repository_owner }}/kinoite-amd:latest --format '{{range .RepoTags}}{{println .}}{{end}}' | grep -E '^[0-9]+$' | head -n 1)
          if [ -z "$VERSION" ]; then
            echo "Erro: Versão numérica não detectada no GHCR."
            exit 1
          fi
          echo "fedorav=$VERSION" >> $GITHUB_OUTPUT

      - name: Generate ISO
        uses: jasonn3/build-container-installer@main
        id: build
        with:
          arch: x86_64
          variant: Kinoite
          image_name: kinoite-amd
          image_repo: ghcr.io/${{ github.repository_owner }}
          image_tag: latest
          version: ${{ steps.detect.outputs.fedorav }}
          iso_name: kinoite-amd-nightly.iso 
          secure_boot_key_url: "https://raw.githubusercontent.com/${{ github.repository }}/main/cosign.pub"

      - name: Publish ISO to GHCR
        shell: bash
        run: |
          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/kinoite-iso:latest"
          ISO_FILE="${{ steps.build.outputs.iso_name }}"
          
          echo "FROM scratch" > "${{ steps.build.outputs.iso_path }}/Dockerfile.iso"
          echo "COPY $ISO_FILE /" >> "${{ steps.build.outputs.iso_path }}/Dockerfile.iso"
          
          echo "${{ github.token }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin
          podman build -f "${{ steps.build.outputs.iso_path }}/Dockerfile.iso" -t "$IMAGE_NAME" "${{ steps.build.outputs.iso_path }}"
          podman push "$IMAGE_NAME"
