name: build-nvidia
on:
  pull_request:
  workflow_dispatch:

jobs:
  build-nvidia:
    uses: ./.github/workflows/base/build-image.yml
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      job_name: Build Custom NVIDIA Image
      recipe: recipe-nvidia.yml
    secrets: inherit
