name: build-amd
on:
  pull_request:
  workflow_dispatch:

jobs:
  build-amd:
    uses: ./.github/build-image.yml
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      job_name: Build Custom AMD Image
      recipe: recipe-amd.yml
    secrets: inherit
